theme: jekyll-theme-minimal
title: [Gahl Shemy]
title_separator: |
description: [Office: East Hall 4828]
minimal_mistakes_skin: sunrise 
show_date: true 
logo: "/assets/images/DSCN1694.jpeg"

markdown: kramdown
kramdown:
    math_engine: katex
